# Generated by Django 3.2.12 on 2022-02-17 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('company_name', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('zip_sn', models.IntegerField(max_length=10)),
                ('email', models.CharField(max_length=100)),
                ('web', models.CharField(max_length=100)),
                ('age', models.IntegerField(max_length=3)),
            ],
        ),
    ]
